vim.keymap.set('ca', 'wsh', 'leftabove vertical')
vim.keymap.set('ca', 'wsj', 'belowright')
vim.keymap.set('ca', 'wsk', 'aboveleft')
vim.keymap.set('ca', 'wsl', 'rightbelow vertical')
vim.keymap.set('ca', 'ee', "expand('')<Left><Left><C-r>=Eatchar('\\s')<CR>")
vim.keymap.set('ca', 'dd', '%:p:h')
--vim.keymap.set('ca', 'ptt', '<[^>]\\+><C-r>=lua Eatspace()<CR>', {desc = 'Pattern: Tag'})
--vim.cmd([[cnorea ptt <[^>]\+><C-r>=Eatchar('\s')<CR>]])
vim.keymap.set('ca', 'ptt', "<[^>]\\+><C-r>=Eatchar('\\s')<CR>")
vim.keymap.set('ca', 'll', "<lt>Leader><C-r>=Eatchar('\\s')<CR>")
vim.keymap.set('ca', 'lll', "<lt>LocalLeader><C-r>=Eatchar('\\s')<CR>")
vim.keymap.set('ca', 'bb', "\\<\\><Left><Left><C-r>=Eatchar('\\s')<CR>")
