vim.opt_local.conceallevel = 2

-- open org file from agenda view will disable cursorline and number, relativenumber
-- [update] now use no (relative)number as default
vim.opt_local.cursorline = true
vim.opt_local.cursorcolumn = false
vim.opt_local.number = false
vim.opt_local.relativenumber = false

vim.opt_local.expandtab = true
vim.opt_local.tabstop = 4

vim.keymap.set('i', 'jlc', '~~<Left>', {buffer = true})
vim.keymap.set('i', 'jlm', '$$<Left>', {buffer = true})

vim.keymap.set('v', '<LocalLeader>b', 'v`>a*<Esc>`<i*<Esc>', {buffer = true})
vim.keymap.set('v', '<LocalLeader>i', 'v`>a/<Esc>`<i/<Esc>', {buffer = true})
vim.keymap.set('v', '<LocalLeader>c', 'v`>a~<Esc>`<i~<Esc>', {buffer = true})
vim.keymap.set('v', '<LocalLeader>m', 'v`>a$<Esc>`<i$<Esc>', {buffer = true})

vim.keymap.set('ca', 'poo', "^\\*\\+", {desc = 'Pattern of Org Node', buffer = true})
vim.keymap.set('ca', 'pott', ":\\zs\\w\\+\\ze:<C-r>=Eatchar('\\s')<CR>", {desc = 'Pattern of Org Tag', buffer = true})

-- ======== back ========

---@desc get infomation of a node from current cursor position
---      !!originally generated by Gemini 3 Pro Preview!!
local function get_node_info()
	-- 1. Get current cursor position
	-- output is {row, col}, row is 1-based
	local cursor = vim.api.nvim_win_get_cursor(0)
	local current_row = cursor[1] - 1 -- Convert to 0-based for API usage

	-- 2. Find the Headline (Search backwards)
	-- We search from current line up to line 0
	local headline_row = -1
	local headline_text = ""
	
	-- Iterate backwards to find line starting with '*'
	for i = current_row, 0, -1 do
		local line = vim.api.nvim_buf_get_lines(0, i, i + 1, false)[1]
		if line and line:match("^%*+%s") then
			headline_row = i
			headline_text = line
			break
		end
	end

	if headline_row == -1 then
		print("No Org headline found above cursor.")
		return
	end

	-- 3. Parse Headline (Title and Tags)
	-- Remove the stars (e.g., "** ")
	local clean_text = headline_text:match("^%*+%s+(.*)") or headline_text

	-- Extract Tags (match text at end wrapped in ::)
	local tags = clean_text:match(":(%g+):$") -- %g means printable chars
	local title = clean_text

	if tags then
		-- Remove tags from title
		title = clean_text:gsub(":%g+:$", "")
		-- Clean up whitespace
		title = vim.trim(title)
	end

	-- 4. Parse Properties (Search forward from headline)
	local props = {}
	local in_drawer = false
	
	-- We scan lines below the headline until we hit another headline or end of file
	local limit = vim.api.nvim_buf_line_count(0)
	
	for i = headline_row + 1, limit - 1 do
		local line = vim.api.nvim_buf_get_lines(0, i, i + 1, false)[1]

		-- Stop if we hit the next headline
		if line:match("^%*+%s") then break end

		-- Check for Property Drawer start/end
		if line:match("^%s*:PROPERTIES:%s*$") then
			in_drawer = true
		elseif line:match("^%s*:END:%s*$") then
			in_drawer = false
			break -- optimization: stop scanning if drawer ends
		elseif in_drawer then
			-- Capture Key and Value:  :KEY: Value
			local key, value = line:match("^%s*:(%w+):%s*(.*)")
			if key then
				props[key] = value
			end
		end
	end

	-- 5. Output the result
	-- print("Title: " .. title)
	-- print("Tags: " .. (tags or "None"))
	-- print("ID: " .. (props["ID"] or "None"))
	
	-- Optional: return table for use elsewhere
	return { title = title, tags = tags, properties = props }
end

---@desc location list
local function find_backlinks()
	local properties = get_node_info().properties
	local id = properties["ID"]
	if id == nil then
		vim.notify("[org] find_backlinks: ID not generated")
	else
		-- print("-torg '\\[\\[id:"..id.."\\]\\[.*\\]\\]' "..vim.env.org_path)
		vim.cmd.lgrep{"-torg '\\[\\[id:"..id.."\\]\\[.*\\]\\]' "..vim.env.org_path, bang = true, mods = {silent = true}}
		vim.cmd.lopen()
	end
end

vim.keymap.set('n', '<LocalLeader>B', find_backlinks, {buffer = true})

-- BUG [with blink.cmp] 手动编辑 link 时卡死, 详见 blink.cmp 的配置
--     temp = 对 org 禁用 blink.cmp
-- local ok, _ = pcall(require, 'blink.cmp')
-- if ok then
-- 	vim.b.completion = false
-- end

-- [deprecated] rely on plugin "sniprun"
-- vim.keymap.set('n', '<leader>r', '?^\\s*#+begin_src?1<Cr>V/^\\s*#+end_src/-1<Cr>:SnipRun<Cr>', {buffer = true, desc = 'Run current src block (with SnipRun)'})

--vim.keymap.set('n', '<leader>R', ':e!', {buffer = true})

-- abbreviation

--vim.keymap.set('ia', 'h3', '***', {buffer = true})
